version: '3.1'
services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8081:80
    networks:
      - webnet
  db:
    container_name: mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=jedzonko
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=jedzonko
    ports:
      - '3306:3306'
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      - webnet

  jedzonko-back-end:
    container_name: jedzonko-back-end
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - '5000'
    ports:
      - '5000:5000'
      - '9229:9229'
    command: yarn start:debug
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DB=jedzonko
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - PORT=5000
    links:
      - db
    networks:
      - webnet

networks:
  webnet:
volumes:
  db-vol:
